CREATE TABLE Ugovor
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	KIme VARCHAR(128) NOT NULL,
	Trajanje INT NOT NULL,
	Popust INT NOT NULL,
	Gratis INT NOT NULL,
	Stat INT NOT NULL,
	Kreirano DATETIME NOT NULL,
	Net INT NULL,
	Iptv INT NULL,
	Voip INT NULL,
	FOREIGN KEY (Net) REFERENCES Paket(Id),
	FOREIGN KEY (Iptv) REFERENCES Paket(Id),
	FOREIGN KEY (Voip) REFERENCES Paket(Id)
);